### ISSUE TITLE
회원가입 기능 테스트 코드 작성

### ISSUE THREAD

**Issue by syoh98** [f-lab-edu/go-table#10]
## 📝 TODO
회원가입 성공 및 실패에 대한 단위 테스트 코드 작성
* Controller
  - [x] 아이디 중복체크 시 중복되지 않은 아이디를 입력했을 때 200 OK를 반환한다.
  - [x] 아이디 중복체크 시 중복된 아이디를 입력했을 때 DuplicatedIdException 예외를 발생시킨다.
  - [x] 회원가입 성공 시 201 Created를 반환한다.
* Service
  - [x] 아이디 중복체크 시 중복된 아이디일 경우 true를 반환한다.
  - [x] 아이디 중복체크 시 중복되지 않은 아이디일 경우 false를 반환한다.

## 📝 참고
* 단위 테스트는 POJO(Plain Old Java Object)의 방식으로 테스트를 진행한다.
  * `@Mock`, `@MockBean`, `@SpyBean`으로 테스트 코드를 작성할 경우 반드시 Spring Framework 또는 Mock Framework 위에서 동작해야 한다.
  * 이는 Mock Framework의 구현(버전)이 변경되면 테스트 코드가 깨지는 문제가 발생`(=멱등성이 유지되지 않음)`한다.
  * 위와 같은 단점을 보완하기 위해 POJO의 방식으로 단위테스트를 진행한다.
