### ISSUE TITLE
회원가입 기능 개발

### ISSUE THREAD

**Issue by syoh98** [f-lab-edu/go-table#4]
<img src="https://github.com/f-lab-edu/go-table/assets/76934280/cb30b4c0-e07b-4348-a22e-98334ceebf29" width="600"/>

## 📝 요구사항
* 로그인하지 않은 상태(인증되지 않은 상태)인 경우 회원가입 페이지에 접속할 수 있다.
* 중복되지 않은 아이디로 회원가입 요청을 하면 회원가입에 성공한다.
  * 중복되지 않은 아이디: member 테이블에 동일한 아이디가 있는지 없는지 확인한다.
  * 비밀번호 암호화 진행

## 📝 플로우차트
![image](https://github.com/f-lab-edu/go-table/assets/76934280/002bcdda-24b8-4290-8a00-304dc9d5b1ed)

## 📝 TODO

* MyBatis 연동
* 회원가입 API 정의

  |기능|HTTP 메서드|API Path|Request|Response|
  |---|---|---|---|---|
  |회원가입|POST|``` /members/signup ```|-|-|
  * Request
    * Request Elements
      |파라미터|타입|필수여부|설명|
      |---|---|---|---|
      |name|String|필수|이름|
      |id|String|필수|아이디|
      |password|String|필수|비밀번호|
      |phone|String|필수|전화번호|
    * Body
      ```json
      {
        "name": "오소영",
        "id": "syoh98",
        "password": "A2983Jd46x",
        "phone": "010-1111-2222"
      }
      ```
  * Reponse
    * Response Elements
      |필드|타입|필수여부|설명|
      |---|---|---|---|
      |status|String|필수|상태코드|
      |data|T|필수|데이터|
      |message|String|필수|메세지|
    * Body
      * 회원가입 성공 **(201 Created)**
        ```json
        {
          "status": "success",
          "data": {
             "name": "오소영",
             "id": "syoh98",
             "password": "A2983Jd46x",
             "phone": "010-1111-2222"
          }, 
          "message": "회원가입 성공"
        }
        ```
      * 회원가입 실패 - 유효성 검사 **(400 Bad Request)**
         ```json
        {
          "status": "fail",
          "data": null,
          "message": {
            "id": "아이디는 영문, 숫자만 가능하며 4 ~ 12자리여야 합니다.",
            "phone": "전화번호 형식은 010-0000-0000입니다."
          },
        }
      * 회원가입 실패 - 중복된 id **(409 Conflict)**
         ```json
        {
          "status": "fail",
          "data": null,
          "message": "중복된 id 입니다."
        }

* 회원가입 기능 
  - [x] 회원 DTO 생성
  - [x] 유효성 검사
    * 이름 
      - [x] null, "", 공백을 허용하지 않는다
    * 전화번호
      - [x] null, "", 공백을 허용하지 않는다
      - [x] 중복되지 않아야 한다
      - [x] 숫자 3자리-숫자 3자리 또는 4자리-숫자 4자리의 형식을 가져야 한다(ex) 010-1111-2222)
      - [x] 맨 앞 숫자 3자리는 01로 시작해야한다
    * 아이디
      - [x] null, "", 공백을 허용하지 않는다
      - [x] 영문, 숫자만 가능하다
      - [x] 4~12자리의 범위를 가져야 한다
    * 비밀번호
      - [x] null, "", 공백을 허용하지 않는다
      - [x] 영문, 숫자, 특수문자가 적어도 1개 이상이어야한다
      - [x] 8~30자리의 범위를 가져야 한다
   - [x] 비밀번호 암호화 방식
       암호화 방식을 비교해보고 어떤 암호화 방식을 선택할지 결정

**Comment by f-lab-maverick** [comment]
400 실패시 어떤 형태로 에러가 내려가는지도 중요합니다.
클라이언트에서 400 에러를 받은 상태로 서버에서 아무런 메세지도 보내주지 않는다면 도대체 어느 부분이 잘못되었는지 찾을 수 없으니까요. 400대 validation error가 발생할 경우 어떻게 에러를 처리해줄지도 한번 적어주시면 완료될 것으로 보입니다~~
