### ISSUE TITLE
로그인 기능 개발

### ISSUE THREAD

**Issue by syoh98** [f-lab-edu/go-table#5]
<img src="https://github.com/f-lab-edu/go-table/assets/76934280/985661f7-ba54-4ecd-8fff-78f56befe11b" width="700"/>

## 📝 요구사항
* 입력한 아이디, 비밀번호가 일치하는 회원이 있을 경우 로그인에 성공한다.
* 세션에 회원 id가 저장되어 있을 경우 로그아웃에 성공한다.

## 📝 플로우차트
![image](https://github.com/f-lab-edu/go-table/assets/76934280/a8fba540-20ef-429f-aa52-a67821466a71)

## 📝 고민했던 사항
  * **로그인 기능 구현 방법 선택**
    `Session`과 `Token`의 방법 중 `Session`을 선택했습니다.
    * 세션 방식은 사용자의 정보를 서버에서 관리하기 때문에 `Stateful`하고, 토큰 방식은 사용자의 정보를 서버에서 관리하지 않기 때문에 `Stateless`하다는 특징을 갖고 있습니다.   
      하지만 토큰방식은 서버에서 사용자의 화이트리스트/블랙리스트를 관리하는 경우(사용자의 상태를 서버에서 관리)와 `Refresh Token`을 DB에서 관리하는 이유로 토큰 방식은 더 이상 `Stateless`하지 않아지고 세션 방식과 다를 바가 없어집니다.
      따라서 보안적인 측면을 더할수록 토큰과 차이가 없다고 생각하여 `Session`을 선택했습니다.
  * **확장성 있는(`Scalability`) 서비스를 위한 `Session Storage` 선택**
    *  go-table은 한정된 인원만이 예약 가능한 시스템으로, 트래픽이 과부하될 경우 **서버의 확장을 통해 유연한 대응이 가능**한 `Scale out`의 환경을 가정했습니다. 
    * Scale out 방식의 문제점인 **데이터 정합성**을 해결하는 방법(`Sticky Session`, `Session Clustering`, `Session Storage`) 중 세션을 서버의 메모리에 저장하지 않고 별도의 저장소에 저장하여 서버의 부하를 줄이고, 특정 서버에 장애가 발생해도 다른 서버에서 세션을 사용하는데 지장이 없는 `Session Storage`의 방법을 선택했습니다.
    * Session Storage의 세션 데이터를 저장하는 주체로 동시 접근이 가능한 DBMS(RDBMS, NoSQL) 중 **Scale out에 유리한** NoSQL이 적절하다 판단하였고, key-value 형태인 세션 데이터를 저장하기에 편하고 빈번한 입출력이 발생했을 때 빠른 성능을 보이는 `In-memory DB`를 선택했습니다.
    * In-memory DB인 `Memcached`과 `Redis` 중 Session Storage에 장애가 발생할 경우 Master-Slave Replication 기능과 AOF, RDB를 통해 데이터 유실 없이 유연한 대응이 가능하고, Session Storage를 사용할 때 읽기 작업이 더 많을 것으로 예상되어 읽기 작업 시 성능이 더 좋은 `Redis`를 선택했습니다.
* **공통 관심사(cross-cutting concern) 처리 방법 선택**
  * 모든 컨트롤러 로직에 로그인 여부를 확인하는 코드를 작성하는 것은 비효율적이므로 공통관심사를 `Interceptor`로 처리했습니다.
  * go-table은 회원가입과 로그인을 제외한 대부분의 기능에 대해 로그인 상태를 요구하는 예약 서비스로 인터셉터에서 패턴을 지정하여 URL을 관리하는 것이 간편하다고 생각했습니다.
    또한 `Filter`는 스프링 범위 밖에서 처리되기 때문에 스프링에 의해 필터링되는 요청들도 전부 받는 것과 달리 인터셉터는 스프링 컨텍스트에서 동작하기 때문에 성능적인 면에서 이점이 있을거라 판단하여 `Interceptor`를 사용했습니다.

## 📝 TODO
* **로그인 API 정의**
  |기능|HTTP 메서드|API Path|Request|Response|
  |---|---|---|---|---|
  |로그인|POST|` /members/login`|-|-|
  * Request
    * Request Elements
      |파라미터|타입|필수여부|설명|
      |---|---|---|---|
      |id|String|필수|아이디|
      |password|String|필수|비밀번호|
    * Body
      ```json
      {
        "id": "syoh98",
        "password": "A2983Jd46x"
      }
      ```
  * Response
    * Response Elements
      |필드|타입|필수여부|설명|
      |---|---|---|---|
      |status|String|필수|상태코드|
      |data|T|필수|데이터|
      |message|String|필수|메세지|
    * 로그인 성공 **(200 OK)**
       ```json
         {
           "status": "success",
           "data": {
             "id": "syoh98",
             "password": "q2w3e4r"
           },
           "message": "로그인 성공"
         }
       ```
    * 로그인 실패 - 유효성 검사 **(400 Bad Request)**
       ```json
        {
          "status": "fail",
          "data": null,
          "message": {
            "id": "아이디는 특수문자 입력이 불가능하며 최대 12자리까지 입력 가능합니다.",
            "password": "비밀번호는 최대 30자리까지 입력 가능합니다."
          }
        }
        ```
    * 로그인 실패 - 존재하지 않는 id **(400 Bad Request)**
       ```json
        {
          "status": "fail",
          "data": null,
          "message": "존재하지 않는 id입니다."
        }
        ```
    * 로그인 실패 -  일치하지 않는 password **(400 Bad Request)**
       ```json
        {
          "status": "fail",
          "data": null,
          "message": "비밀번호가 일치하지 않습니다."
        }
        ```
* **로그아웃 API 정의**
  |기능|HTTP 메서드|API Path|Request|Response|
  |---|---|---|---|---|
  |로그아웃|GET|` /members/logout`|-|-|
  * Response
    * Response Elements
      |필드|타입|필수여부|설명|
      |---|---|---|---|
      |status|String|필수|상태코드|
      |data|T|필수|데이터|
      |message|String|필수|메세지|
    * 로그아웃 성공 **(200 OK)**
       ```json
        {
          "status": "success",
          "data": null,
          "message": "로그아웃 성공"
        }
        ```
    * 로그아웃 실패 - 로그인하지 않은 상태 **(401 Unauthorized)**
       ```json
        {
          "status": "fail",
          "data": null,
          "message": "로그인이 필요한 기능입니다."
        }
        ```
* 로그인 기능
   - [x] 유효성 검사
  * 아이디
   - [x] null, "", 공백을 허용하지 않는다
   - [x] 최대 12자리까지 입력이 가능하다
   - [x] 특수문자 입력을 허용하지 않는다
  * 비밀번호
   - [x] null, "", 공백을 허용하지 않는다
   - [x] 최대 30자리까지 입력이 가능하다
* 로그인/로그아웃 성공 및 실패에 대한 단위 테스트 코드 작성
  * Controller
   - [x] 로그인 성공 시 200 OK를 반환한다.
   - [x] 로그인 실패 시 MemberNotFoundException 예외를 발생시킨다.
  * Service
   - [x] 해당 id로 가입한 회원이 존재하는 경우 가입한 Member를 반환한다.
   - [x] 해당 id로 가입한 회원이 존재하지 않는 경우 MemberNotFoundException 예외를 발생시킨다.
   - [x] 해당 id로 가입한 회원이 존재하고 비밀번호가 일치하는 경우 TRUE를 반환한다.
   - [x] 해당 id로 가입한 회원이 존재하고 비밀번호가 일치하지 않는 경우 FALSE를 반환한다.
   - [x] 로그인에 성공하는 경우 세션에 id를 저장한다.
   - [x] 로그아웃에 성공하는 경우 세션에 저장된 id를 제거한다.
